### ISSUE TITLE
Pls Create a discord server 

### ISSUE THREAD

**Issue by x-TheFox** [SofiaRedmond/Slimefun-Geyser#11]
a discord server for contacting you and know about updates will be great something simple is enough

**Comment by SofiaRedmond** [comment]
🇬🇧 I thought about doing that, but creating a Discord server just to use a single text chat seems a bit excessive, like putting rocket propulsion in a wheelchair.

🇪🇦 Pensé en hacer eso, pero crear un servidor de Discord solo para usar un único chat de texto me parece un poco excesivo, como ponerle propulsión por cohete a una silla de ruedas.

**Comment by x-TheFox** [comment]
um fair enough but it would be useful
