### ISSUE TITLE
Test Server & No Textures

### ISSUE THREAD

**Issue by IceGamerYT** [SofiaRedmond/Slimefun-Geyser#16]
Heya, 2 things

1. The textures dont work for me, I dont exactly know why but i've tried 2 things
Simply using the extension did nothing
using a different item-models.yml on slimefun made all the items invisible
Did i do anything wrong? Am i missing a step?

2. I have a server hosted on google cloud, if you dont mind i can let you use it for testing, although me and my friends will also be playing on it

**Comment by SofiaRedmond** [comment]
1.- You need a standard Slimefun setup, this extension can't work correctly if the Slimefun plugin isn't correctly set.

1.1.- Check that's the clients be required to download the resource pack on join.

2.- where is your server located? (country)

**Comment by IceGamerYT** [comment]
Thanks for the quick reply

1. I see, that means the server didnt download the texture, what should i do to fix that?

2. South America, Brazil - São Paulo

**Comment by SofiaRedmond** [comment]
1.- [Follow this link](https://github.com/SofiaRedmond/Slimefun-Geyser/wiki#texture-pack) to learn how to set the RP on your server.

2.- i'll need access to the server storage and console, for permissions and testing tasks.

**Comment by IceGamerYT** [comment]
1. Oh i never realized there was a wiki lol, my bad fr

2. Alright, Although as a i said we'll be playing alongside your testing

Its late here so i'll be going, but tomorrow we can iron out the details. Thanks for the help!

Discord: Not_Ice__#0059

**Comment by IceGamerYT** [comment]
After adding the manifest and adding the texture pack, it all works now! Thanks alot

My discord tag is on the comment above, add me there so we can continue discussing the test server
