### ISSUE TITLE
Recource pack is broken.

### ISSUE THREAD

**Issue by J1coding** [SofiaRedmond/Slimefun-Geyser#20]
The texture pack is not displayed correctly, some textures are glitchy, not there or on the wrong items.

**Comment by J1coding** [comment]
![imaaaaaaaaaaaaaaage](https://github.com/SofiaRedmond/Slimefun-Geyser/assets/113301471/5fe9b617-8f9c-4192-b49f-a6feb97548b4)

**Comment by SofiaRedmond** [comment]
You must use the extension, mappings file are deprecated.
