### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by just-a-pony** [SofiaRedmond/Slimefun-Geyser#3]
I tried to understand how to use this,but I still haven't figured out. Could anyone tell me something about it?

**Comment by SofiaRedmond** [comment]
First Step:
You must download a GeyserMC plugin for Java Edition server what supports custom mappings (You can do that from here: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/feature%252Fextensions/)
![image](https://user-images.githubusercontent.com/86848962/177206407-be4d6b6e-d338-4a76-865d-0fa52dce9d18.png)

Second Step:
When your server starts, the plugin will generate a folder named "custom_mappings", you must paste the mappings from this repo ([GeyserCustomMappings/custom_mappings](https://github.com/SofiaRedmond/Slimefun-Geyser/tree/main/GeyserCustomMappings/custom_mappings)) on that folder.
![image](https://user-images.githubusercontent.com/86848962/177206476-2e477b26-4861-42b1-a118-bc6c8812cee0.png)

Third Step: 
That's all on server side. On client side you must add the Manifest.json to the [SlimefunBedrockRP](https://github.com/SofiaRedmond/Slimefun-Geyser/tree/main/SlimefunBedrockRP) to create a valid resource pack for the players who will join the server. (More info about manifest file: https://docs.microsoft.com/en-us/minecraft/creator/documents/resourcepack#create-a-manifest-file)

Additionally, you can put the RP to the "Packs" folder to install the RP on join on clients.
![image](https://user-images.githubusercontent.com/86848962/177206297-68b36149-758d-4e96-8c30-6790149d201c.png)

Stay tuned, this repository updates mappings periodically and adds new objects or missing objects.
