### ISSUE TITLE
这个材质包在1.19.40上无法正常运行This Slimefun-Resource-Pack does not work properly on 1.19.40

### ISSUE THREAD

**Issue by MrEriczheng** [SofiaRedmond/Slimefun-Geyser#4]
这个材质包在1.19.40上无法正常运行
This Slimefun-Resource-Pack does not work properly on 1.19.40
物品是错乱的，矿粉是重灾区
The object is disordered.Mineral powder is the hardest hit area
![-2e7ed432228e7918](https://user-images.githubusercontent.com/72022428/199988327-72a419df-aa55-41de-801e-1c6afad57e20.jpg)

**Comment by SofiaRedmond** [comment]
¡La forma de resolver este bug ha sido encontrada! Primero se consultará en el GitHub de GeyserMC por si se logra hallar un arreglo por ese lado.

**Comment by SofiaRedmond** [comment]
Se ha recibido una respuesta desde GeyserMC.

Se está trabajando en la solución al error ahora.

**Comment by SofiaRedmond** [comment]
This bug is partially solved! Download the extension from [here](https://github.com/SofiaRedmond/Slimefun-Geyser/releases/tag/Pre-release)! / Este error fue resuelto parcialmente! Descarga la extensión desde [aquí](https://github.com/SofiaRedmond/Slimefun-Geyser/releases/tag/Pre-release)!
