### ISSUE TITLE
Texture is still confused

### ISSUE THREAD

**Issue by asdzxc233** [SofiaRedmond/Slimefun-Geyser#5]
![Screenshot_2022-12-30-08-09-01-112_com mojang minecraftpe](https://user-images.githubusercontent.com/96332848/210022915-7e1e8bf2-715c-4739-bff2-0abd697cb87d.jpg)
![Screenshot_2022-12-30-08-08-53-873_com mojang minecraftpe](https://user-images.githubusercontent.com/96332848/210022918-a8d1a2ca-5e86-40a1-9f98-d9c026541891.jpg)
![Screenshot_2022-12-30-08-08-48-443_com mojang minecraftpe](https://user-images.githubusercontent.com/96332848/210022919-2c03334d-b594-42b6-912f-64d841b37f0b.jpg)
![Screenshot_2022-12-30-08-08-38-398_com mojang minecraftpe](https://user-images.githubusercontent.com/96332848/210022921-fcb34e87-07bb-405b-9980-f8bf6034d2cc.jpg)
![Screenshot_2022-12-30-08-08-34-824_com mojang minecraftpe](https://user-images.githubusercontent.com/96332848/210022924-212defb4-e66a-4e36-9b74-e0982c364d8a.jpg)
![Screenshot_2022-12-30-08-08-28-278_com mojang minecraftpe](https://user-images.githubusercontent.com/96332848/210022925-83f2c1cf-7d39-41cf-bc75-81adde405893.jpg)
![Screenshot_2022-12-30-08-08-19-541_com mojang minecraftpe](https://user-images.githubusercontent.com/96332848/210022926-3ca6fc82-8376-499a-a07e-090bf06e6ab6.jpg)
![Screenshot_2022-12-30-08-08-10-923_com mojang minecraftpe](https://user-images.githubusercontent.com/96332848/210022927-6360d86a-44b4-45f4-8e9a-a1f552b16fe8.jpg)
![Screenshot_2022-12-30-08-07-54-547_com mojang minecraftpe](https://user-images.githubusercontent.com/96332848/210022928-45553eaf-1828-4573-a693-edc93d6aa066.jpg)
![Screenshot_2022-12-30-08-07-50-945_com mojang minecraftpe](https://user-images.githubusercontent.com/96332848/210022930-9fbe6388-f380-4ac4-99cb-8bd6ff848e16.jpg)

**Comment by SofiaRedmond** [comment]
(EN) It looks like a Resource Pack error, have you removed the mappings before installing the extension?

(ES) Parece un error del paquete de recursos, quitaste los mappeos antes de instalar la extensión?

**Comment by asdzxc233** [comment]
yes,i remove it

**Comment by SofiaRedmond** [comment]
(EN) Can you activate the error logger (Minecraft) and send me the log?

(ES) Podrías activar el registro de errores (de  Minecraft) y enviarme el archivo de registro?

**Comment by SofiaRedmond** [comment]
Closed by NO ANSWER
