### ISSUE TITLE
Not work at all

### ISSUE THREAD

**Issue by pearlroy** [SofiaRedmond/Slimefun-Geyser#6]
I used GEYSERMC plugin latest version - 2.1.0-SNAPSHOT (git-master-7905581) 
I followed everything as explained in the wiki, It downloaded files while joining server, but does'nt showed any texture on opening slimefun guide! No textures

**Comment by pearlroy** [comment]
here are the server logs - https://mclo.gs/Doqcybw

**Comment by SofiaRedmond** [comment]
(EN) Can you activate the error logger and show/send me the logs?

(ES) Puedes activar este registro de errores y enviarme o mostrarme el registro?

![Screenshot_20230106-155412_Minecraft.png](https://user-images.githubusercontent.com/86848962/211098357-56b8d6f8-eb4e-4036-94aa-6563fe6da0fa.png)

**Comment by pearlroy** [comment]
Here it is

![Screenshot_2023-01-07-11-33-07-50_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/101255168/211134164-6562c6ec-3e6b-4e31-afb4-b9a2d4e4d775.jpg)
![Screenshot_2023-01-07-11-40-05-17_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/101255168/211134165-f7261e55-d6fe-488f-8a3a-2661077a6854.jpg)
![Screenshot_2023-01-07-11-40-08-23_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/101255168/211134167-6231361b-8e76-4d02-9010-6d06cb9c3af2.jpg)
![Screenshot_2023-01-07-11-40-17-48_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/101255168/211134168-d5cded89-adf3-461b-907f-c1b3d7a8191b.jpg)
![Screenshot_2023-01-07-11-41-17-52_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/101255168/211134169-5b9a67b4-ef71-4378-a3b8-e1ff9e54eb07.jpg)

**Comment by pearlroy** [comment]
![Screenshot_2023-01-07-11-48-52-43_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/101255168/211134315-b5bd143e-880c-4a6b-a3e1-d15781609ca3.jpg)

**Comment by pearlroy** [comment]
I speak and understand English language

**Comment by SofiaRedmond** [comment]
(EN) It looks like the items are registered twice, have you remove the mappings before installing the extension?

(ES) Al parecer los objetos se están registrando dos veces, quitaste los mapeos antes de instalar la extensión?

**Comment by pearlroy** [comment]
How to remove mappings? Like, It's not explained in the wiki, kindly guide me

**Comment by pearlroy** [comment]
I did the mappings part described in the wiki and put the custom_mappings files in the folder of geyser plugin

**Comment by SofiaRedmond** [comment]
(EN) You must install only mappings or extension, not both.

(ES) Debes instalar únicamente los mapeos o bien la extensión, no ambos.

**Comment by pearlroy** [comment]
So, what I can do now?

**Comment by pearlroy** [comment]
Do I remove the extension that I installed and put in extension folder of geyser plugin?

**Comment by pearlroy** [comment]
or I delete custom _mappings that I put in the folder of geyser/custom _mappings

**Comment by SofiaRedmond** [comment]
(EN) You must remove the mappings (from "custom_mappings" folder), those no longer works as expected on latest versions of GeyserMC, and are deprecated.

(ES) Debes eliminar los mapeos (los que están en la carpeta "custom_mappings") ya que no funcionan como deberían en las ultimas versiones de GeyserMC y están obsoletos.

**Comment by pearlroy** [comment]
I deleted all custom mappings in the folder plugins/geyser/custom_mappings and This coming now

![Screenshot_2023-01-07-12-53-44-36_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/101255168/211139242-6c0ad7aa-03d6-4a65-b1cb-ef4422ac1b35.jpg)

![Screenshot_2023-01-07-12-53-08-18_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/101255168/211139244-11a9d38d-6f09-4213-af87-a961de127f86.jpg)

**Comment by pearlroy** [comment]
![IMG_20230107_125807](https://user-images.githubusercontent.com/101255168/211139374-ac5b1215-2acf-4908-8bde-3e5deb7b39cf.jpg)
![IMG_20230107_125820](https://user-images.githubusercontent.com/101255168/211139383-41bd0004-26da-4083-9081-250f9878d2e6.jpg)

**Comment by pearlroy** [comment]
kindly reply

**Comment by pearlroy** [comment]
what should I do next?

**Comment by SofiaRedmond** [comment]
Show me your console logs again pls.

**Comment by pearlroy** [comment]
https://mclo.gs/w2iLHFI

**Comment by SofiaRedmond** [comment]
Have you downloaded the latest GeyserMC version from [here](https://ci.opencollab.dev//job/GeyserMC/job/Geyser/job/master/)?

**Comment by pearlroy** [comment]
Yes, I have latest version which supports 1.19.3 downloaded from official website of geyser

**Comment by PearlRoy** [comment]
The link you shared, is not of official geyser website?

**Comment by pearlroy** [comment]
Is the official one and this one, both different?

**Comment by pearlroy** [comment]
kindly reply

**Comment by pearlroy** [comment]
kindly reply

**Comment by SofiaRedmond** [comment]
I will need a closer view to the issue, please, send me a meessage to me on Telegram.
