### ISSUE TITLE
Slimefun Geyser 

### ISSUE THREAD

**Issue by jefflima1** [SofiaRedmond/Slimefun-Geyser#8]
Hello, how can I install the Slimefun-Geyser texture extension, and the custom skulls need to be enabled in the geyser config?

**Comment by SofiaRedmond** [comment]
🇬🇧 Hi, you can visit the wiki for a quick install guide and you don't need to enable the "custom skull" to get this working, as far as i know.

🇪🇦 Hola, puedes visitar la wiki para ver una guía rápida de instalación y no necesitas activar las cabezas personalizadas para que la extensión funcione hasta donde sé.
