### ISSUE TITLE
Not working, I can’t upload extensions to Aternos please help

### ISSUE THREAD

**Issue by Franki-Shop** [SofiaRedmond/Slimefun-Geyser#9]
How can I make it work without extensions? As far as I know all plugins use custom mapping and they’re working as intended.  Please fix this besties 💕

**Comment by SofiaRedmond** [comment]
🇬🇧 Hi n.n you can try to use the custom mappings if you are using an older version of GeyserMC, but if you want to use on newer versions you can't, it will be bugged.

🇪🇦 Hola n.n
Puedes usar los mapeos personalizados si estás usando una versión antigua de GeyserMC, de otra forma no, porque no funcionará correctamente.

**Comment by SofiaRedmond** [comment]
🇬🇧 I am very sorry to hear that you have that problem, but it is not something that I can solve, one of the rules of Aternos is that you can not upload custom files or those that can be uploaded are very limited.

That's Aternos limit, not a bug.

(What you can do about it is use another hosting service or host it on your own machine)

🇪🇦 Lamento mucho oir que tengas ese problema, pero no es algo que yo pueda arreglar, una de las reglas de Aternos es que no puedes subir archivos personalizados o que aquellos que se puedan subir sean muy limitados.

Es un límite de Aternos, no es un bug.

(Lo que puedes hacer al respecto es usar otro servico de alojamiento o alojarlo en tu propia maquina)
